visualizer_path: 'C:\\Users\\qw12a\\AppData\\Roaming\\fnm\\node-versions\\v22.11.0\\installation\\mmdc.cmd'
nupkg_path: 'C:\\Users\\qw12a\\Desktop\\Task 2\\newtonsoft.json.13.0.3.nupkg'
output_image_path: 'dependencies_grap.png'