graph TD;
    newtonsoft.json.13.0.3.nupkg --> Microsoft.CSharp;
    newtonsoft.json.13.0.3.nupkg --> NETStandard.Library;
    newtonsoft.json.13.0.3.nupkg --> System.ComponentModel.TypeConverter;
    newtonsoft.json.13.0.3.nupkg --> System.Runtime.Serialization.Primitives;
    newtonsoft.json.13.0.3.nupkg --> System.Runtime.Serialization.Formatters;
    newtonsoft.json.13.0.3.nupkg --> System.Xml.XmlDocument;
